# Generated by Django 5.2.4 on 2025-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllInOneAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aioa_color_code', models.CharField(blank=True, default='', help_text='You can customize the ADA Widget color. For example: #FF5733', max_length=50, verbose_name='Hex color code')),
                ('aioa_place', models.CharField(blank=True, choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('middle_left', 'Middle Left'), ('middle_center', 'Middle Center'), ('middle_right', 'Middle Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='bottom_right', max_length=100, verbose_name='Where would you like to place the accessibility icon on your site')),
                ('aioa_size', models.CharField(choices=[('regular', 'Regular Size'), ('oversized', 'Oversized')], default='regular', max_length=20, verbose_name='Icon Size')),
            ],
            options={
                'verbose_name': 'All in One Accessibility Settings',
                'verbose_name_plural': 'All in One Accessibility Settings',
            },
        ),
    ]
