# Generated by Django 5.2.4 on 2025-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='enable_widget_icon_position',
            field=models.BooleanField(default=True, verbose_name='Enable Precise accessibility widget icon position'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_size',
            field=models.CharField(choices=[('regular', 'Regular Size'), ('oversized', 'Oversized')], default='regular', max_length=20, verbose_name='Select Widget Size'),
        ),
    ]
