# Generated by Django 4.1.9 on 2023-06-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="menu_icons/",
                verbose_name="Menu Icon Image",
            ),
        ),
    ]
