# Generated by Django 4.1.9 on 2023-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0002_all_in_one_accessibility_aioa_icon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.ImageField(
                blank=True,
                default="favicon.png",
                null=True,
                upload_to="menu_icons/",
                verbose_name="Menu Icon Image",
            ),
        ),
    ]
