# Generated by Django 5.2.4 on 2025-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0002_allinoneaccessibility_enable_widget_icon_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_color_code',
            field=models.CharField(blank=True, default='', help_text='You can customize the ADA Widget color. For example: #FF5733', max_length=50, verbose_name='Hex Color Code'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_size',
            field=models.CharField(choices=[('regular', 'Regular Size'), ('oversize', 'Oversize')], default='oversize', max_length=20, verbose_name='Select Widget Size'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='enable_widget_icon_position',
            field=models.BooleanField(default=False, verbose_name='Enable Precise accessibility widget icon position'),
        ),
    ]
