# Generated by Django 5.2.4 on 2025-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0003_alter_allinoneaccessibility_aioa_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_place',
            field=models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('middle_left', 'Middle Left'), ('middle_center', 'Middle Center'), ('middle_right', 'Middle Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='bottom_right', max_length=100, verbose_name='Where would you like to place the accessibility icon on your site'),
        ),
    ]
