# Generated by Django 4.1.9 on 2023-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0003_alter_all_in_one_accessibility_aioa_icon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top_left", "Top left"),
                    ("top_center", "Top Center"),
                    ("top_right", "Top Right"),
                ],
                
                max_length=100,
                verbose_name="Where would you like to place the accessibility icon on your site",
            ),
        ),
    ]
