# Generated by Django 5.2.4 on 2025-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0004_alter_allinoneaccessibility_aioa_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_icon_type',
            field=models.CharField(choices=[('aioa-icon-type-1', 'Icon Type 1'), ('aioa-icon-type-2', 'Icon Type 2'), ('aioa-icon-type-3', 'Icon Type 3')], default='aioa-icon-type-1', max_length=50, verbose_name='Icon Type'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='enable_icon_custom_size',
            field=models.BooleanField(default=False, verbose_name='Enable Icon Custom Size'),
        ),
    ]
