# Generated by Django 4.1.9 on 2023-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0004_alter_all_in_one_accessibility_aioa_icon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
