# Generated by Django 5.2.4 on 2025-07-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0005_allinoneaccessibility_aioa_icon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_license_Key',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='License Key'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_right',
            field=models.CharField(blank=True, choices=[('to_the_bottom', 'Top the bottom'), ('to_the_top', 'To the top')], verbose_name='To the bottom'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_icon_type',
            field=models.CharField(choices=[('aioa-icon-type-1', 'Icon Type 1'), ('aioa-icon-type-2', 'Icon Type 2'), ('aioa-icon-type-3', 'Icon Type 3'), ('aioa-icon-type-4', 'Icon Type 4'), ('aioa-icon-type-5', 'Icon Type 5'), ('aioa-icon-type-6', 'Icon Type 6'), ('aioa-icon-type-7', 'Icon Type 7'), ('aioa-icon-type-8', 'Icon Type 8'), ('aioa-icon-type-9', 'Icon Type 9'), ('aioa-icon-type-10', 'Icon Type 10'), ('aioa-icon-type-11', 'Icon Type 11'), ('aioa-icon-type-12', 'Icon Type 12'), ('aioa-icon-type-13', 'Icon Type 13'), ('aioa-icon-type-14', 'Icon Type 14'), ('aioa-icon-type-15', 'Icon Type 15'), ('aioa-icon-type-16', 'Icon Type 16'), ('aioa-icon-type-17', 'Icon Type 17'), ('aioa-icon-type-18', 'Icon Type 18'), ('aioa-icon-type-19', 'Icon Type 19'), ('aioa-icon-type-20', 'Icon Type 20'), ('aioa-icon-type-21', 'Icon Type 21'), ('aioa-icon-type-22', 'Icon Type 22'), ('aioa-icon-type-23', 'Icon Type 23'), ('aioa-icon-type-24', 'Icon Type 24'), ('aioa-icon-type-25', 'Icon Type 25'), ('aioa-icon-type-26', 'Icon Type 26'), ('aioa-icon-type-27', 'Icon Type 27'), ('aioa-icon-type-28', 'Icon Type 28'), ('aioa-icon-type-29', 'Icon Type 29')], default='aioa-icon-type-1', max_length=50, verbose_name='Icon Type'),
        ),
    ]
