# Generated by Django 4.1.9 on 2023-06-15 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0006_all_in_one_accessibility_aioa_icon_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
        ),
    ]
