# Generated by Django 5.2.4 on 2025-07-17 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0006_allinoneaccessibility_aioa_license_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_bottom',
            field=models.CharField(choices=[('to_the_bottom', 'Top the bottom'), ('to_the_top', 'To the top')], default='to_the_bottom', verbose_name='To the bottom'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_bottom_px',
            field=models.PositiveSmallIntegerField(default=20, help_text='Value range: 0–250px', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Bottom offset (PX)'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_right_px',
            field=models.PositiveSmallIntegerField(default=20, help_text='Value range: 0–250px', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Right offset (PX)'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_right',
            field=models.CharField(choices=[('to_the_left', 'Top the Right'), ('to_the_right', 'To the Left')], default='to_the_left', verbose_name='To the left'),
        ),
    ]
