# Generated by Django 5.2.4 on 2025-07-17 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0007_allinoneaccessibility_to_the_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_size_value',
            field=models.PositiveSmallIntegerField(default=20, help_text='20 - 150px are permitted values', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(150)], verbose_name='Select exact icon size (PX)'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_bottom_px',
            field=models.PositiveSmallIntegerField(default=20, help_text='0 - 250px are permitted values', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Bottom offset (PX)'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_right_px',
            field=models.PositiveSmallIntegerField(default=20, help_text='0 - 250px are permitted values', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Right offset (PX)'),
        ),
    ]
