# Generated by Django 5.2.4 on 2025-07-17 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0008_allinoneaccessibility_aioa_size_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_icon_size',
            field=models.CharField(choices=[('aioa-big-icon', 'Big'), ('aioa-medium-icon', 'Medium'), ('aioa-default-icon', 'Default'), ('aioa-small-icon', 'Small'), ('aioa-extra-small-icon', 'Extra Small')], default='aioa-default-icon', help_text='This size preview will change according to the selected icon type.', max_length=50, verbose_name='Icon Size'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_size_value',
            field=models.PositiveSmallIntegerField(default=50, help_text='20 - 150px are permitted values', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(150)], verbose_name='Select exact icon size (PX)'),
        ),
    ]
