# Generated by Django 4.1.9 on 2023-06-15 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0009_alter_all_in_one_accessibility_aioa_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="all_in_one_accessibility",
            name="aioa_icon",
        ),
        migrations.RemoveField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
        ),
    ]
