# Generated by Django 5.2.4 on 2025-07-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0009_allinoneaccessibility_aioa_icon_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_icon_size',
            field=models.CharField(choices=[('aioa-big-icon', 'Big'), ('aioa-medium-icon', 'Medium'), ('aioa-default-icon', 'Default'), ('aioa-small-icon', 'Small'), ('aioa-extra-small-icon', 'Extra Small')], default='aioa-default-icon', max_length=50, verbose_name='Icon Size'),
        ),
    ]
