# Generated by Django 4.1.9 on 2023-06-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0010_remove_all_in_one_accessibility_aioa_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_in_one_accessibility",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
