# Generated by Django 4.1.9 on 2023-06-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0011_all_in_one_accessibility_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="gender",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
