# Generated by Django 5.2.4 on 2025-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0011_alter_allinoneaccessibility_aioa_icon_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
