# Generated by Django 5.2.4 on 2025-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0012_allinoneaccessibility_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinoneaccessibility',
            name='aioa_license_Key',
        ),
        migrations.RemoveField(
            model_name='allinoneaccessibility',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_right',
            field=models.CharField(choices=[('to_the_left', 'To the Right'), ('to_the_right', 'To the Left')], default='to_the_left', verbose_name='To the left'),
        ),
    ]
