# Generated by Django 4.1.9 on 2023-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0012_alter_all_in_one_accessibility_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="all_in_one_accessibility",
            name="gender",
        ),
        migrations.AddField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
            field=models.CharField(blank=True, choices=[], max_length=200),
        ),
        migrations.AddField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(blank=True, choices=[], max_length=200),
        ),
    ]
