# Generated by Django 4.1.9 on 2023-06-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0013_remove_all_in_one_accessibility_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                max_length=200,
            ),
        ),
    ]
