# Generated by Django 5.2.4 on 2025-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0013_remove_allinoneaccessibility_aioa_license_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
