# Generated by Django 5.2.4 on 2025-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0014_allinoneaccessibility_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_right',
            field=models.CharField(choices=[('to_the_left', 'To the left'), ('to_the_right', 'To the right')], default='to_the_left', verbose_name='To the left'),
        ),
    ]
