# Generated by Django 4.1.9 on 2023-06-17 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0015_remove_all_in_one_accessibility_aioa_icon_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
        ),
    ]
