# Generated by Django 5.2.4 on 2025-08-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0015_alter_allinoneaccessibility_to_the_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinoneaccessibility',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_icon_size',
            field=models.CharField(choices=[('aioa-big-icon', ''), ('aioa-medium-icon', ''), ('aioa-default-icon', ''), ('aioa-small-icon', ''), ('aioa-extra-small-icon', '')], default='aioa-default-icon', help_text='This size preview will change according to the selected icon type.', max_length=50, verbose_name='Icon Size'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_icon_type',
            field=models.CharField(choices=[('aioa-icon-type-1', ''), ('aioa-icon-type-2', ''), ('aioa-icon-type-3', ''), ('aioa-icon-type-4', ''), ('aioa-icon-type-5', ''), ('aioa-icon-type-6', ''), ('aioa-icon-type-7', ''), ('aioa-icon-type-8', ''), ('aioa-icon-type-9', ''), ('aioa-icon-type-10', ''), ('aioa-icon-type-11', ''), ('aioa-icon-type-12', ''), ('aioa-icon-type-13', ''), ('aioa-icon-type-14', ''), ('aioa-icon-type-15', ''), ('aioa-icon-type-16', ''), ('aioa-icon-type-17', ''), ('aioa-icon-type-18', ''), ('aioa-icon-type-19', ''), ('aioa-icon-type-20', ''), ('aioa-icon-type-21', ''), ('aioa-icon-type-22', ''), ('aioa-icon-type-23', ''), ('aioa-icon-type-24', ''), ('aioa-icon-type-25', ''), ('aioa-icon-type-26', ''), ('aioa-icon-type-27', ''), ('aioa-icon-type-28', ''), ('aioa-icon-type-29', '')], default='aioa-icon-type-1', max_length=50, verbose_name='Icon Type'),
        ),
    ]
