# Generated by Django 4.1.9 on 2023-06-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0016_remove_all_in_one_accessibility_aioa_icon_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_in_one_accessibility",
            name="icon_type",
            field=models.CharField(
                choices=[("1", "one"), ("2", "two"), ("3", "three")],
                max_length=50,
                null=True,
            ),
        ),
    ]
