# Generated by Django 4.1.9 on 2023-06-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0019_alter_all_in_one_accessibility_icon_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="icon_size",
            field=models.CharField(
                choices=[
                    ("aioa-big-icon", "big"),
                    ("aioa-medium-icon", "medium"),
                    ("aioa-default-icon", "default"),
                    ("aioa-small-icon", "small"),
                    ("aioa-extra-small-icon", "extra small"),
                ],
                max_length=200,
                null=True,
                verbose_name="Icon Size",
            ),
        ),
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="icon_type",
            field=models.CharField(
                choices=[
                    ("aioa-icon-type-1", "one"),
                    ("aioa-icon-type-2", "two"),
                    ("aioa-icon-type-3", "three"),
                ],
                max_length=200,
                null=True,
                verbose_name="Icon Type",
            ),
        ),
    ]
