# Generated by Django 4.1.9 on 2023-06-17 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0020_alter_all_in_one_accessibility_icon_size_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="all_in_one_accessibility",
            old_name="icon_size",
            new_name="aioa_icon_size",
        ),
        migrations.RenameField(
            model_name="all_in_one_accessibility",
            old_name="icon_type",
            new_name="aioa_icon_type",
        ),
    ]
