# Generated by Django 4.1.9 on 2023-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accessibility",
            "0022_alter_all_in_one_accessibility_aioa_icon_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
