# Generated by Django 4.2.2 on 2023-06-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0025_alter_all_in_one_accessibility_aioa_icon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(
                choices=[
                    (
                        "aioa-icon-type-1",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-icon-type-2",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-2.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-icon-type-3",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-3.svg" width="65" height="65" />',
                    ),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
