# Generated by Django 4.2.2 on 2023-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0027_alter_all_in_one_accessibility_aioa_icon_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
        ),
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(max_length=200, null=True, verbose_name="Icon Type"),
        ),
    ]
