# Generated by Django 4.2.2 on 2023-06-20 07:17

from django.db import migrations, models
import radiogrid.db


class Migration(migrations.Migration):
    dependencies = [
        (
            "accessibility",
            "0028_remove_all_in_one_accessibility_aioa_icon_size_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
            field=models.CharField(max_length=200, null=True, verbose_name="Icon Size"),
        ),
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=radiogrid.db.RadioGridField(
                require_all_fields=True,
                rows=((1, "First"), (2, "Second"), (3, "Third")),
                values=[
                    (
                        "aioa-icon-type-1",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-icon-type-2",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-2.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-icon-type-3",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-3.svg" width="65" height="65" />',
                    ),
                ],
            ),
        ),
    ]
