# Generated by Django 4.2.2 on 2023-06-20 07:21

from django.db import migrations
import radiogrid.db


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0029_all_in_one_accessibility_aioa_icon_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
            field=radiogrid.db.RadioGridField(
                require_all_fields=False,
                rows=((1, ""),),
                values=[
                    (
                        "aioa-big-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="75" height="75" />',
                    ),
                    (
                        "aioa-medium-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-default-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="55" height="55" />',
                    ),
                    (
                        "aioa-small-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="45" height="45" />',
                    ),
                    (
                        "aioa-extra-small-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="35" height="35"/>',
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_type",
            field=radiogrid.db.RadioGridField(
                require_all_fields=False,
                rows=((1, ""),),
                values=[
                    (
                        "aioa-icon-type-1",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-icon-type-2",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-2.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-icon-type-3",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-3.svg" width="65" height="65" />',
                    ),
                ],
            ),
        ),
    ]
