# Generated by Django 4.2.2 on 2023-06-20 10:02

import accessibility.db
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0032_alter_all_in_one_accessibility_aioa_icon_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_in_one_accessibility",
            name="aioa_text",
            field=models.TextField(
                blank=True,
                default=" ",
                help_text='<script>alert("hello");const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size"]\');\n    const sizeOptionsImg = document.querySelectorAll(\'input[name="aioa_icon_size"] + img\');\n    const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type"]\');\n    typeOptions.forEach(option => {\n        option.addEventListener("click", (event) => {\n            sizeOptionsImg.forEach(option2 => {\n                var ico_type = document.querySelector(\'input[name="aioa_icon_type"]:checked\').value;\n                option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n            });\n        });\n    });</script>',
                max_length=100,
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
            field=accessibility.db.RadioGridField(
                require_all_fields=True,
                rows=((1, ""),),
                values=[
                    (
                        "aioa-big-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="75" height="75" />',
                    ),
                    (
                        "aioa-medium-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-default-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="55" height="55" />',
                    ),
                    (
                        "aioa-small-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="45" height="45" />',
                    ),
                    (
                        "aioa-extra-small-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="35" height="35"/>',
                    ),
                ],
            ),
        ),
    ]
