# Generated by Django 4.2.2 on 2023-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0033_all_in_one_accessibility_aioa_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_text",
            field=models.CharField(
                blank=True,
                default=" ",
                help_text='<script>alert("hello");const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size_0"]\');\n    const sizeOptionsImg = document.querySelectorAll(\'input[name="aioa_icon_size_0"] + img\');\n    const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type_0"]\');\n    typeOptions.forEach(option => {\n        option.addEventListener("click", (event) => {\n            sizeOptionsImg.forEach(option2 => {\n                var ico_type = document.querySelector(\'input[name="aioa_icon_type_0"]:checked\').value;\n                option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n            });\n        });\n    });</script>',
                max_length=100,
                verbose_name="",
            ),
        ),
    ]
