# Generated by Django 4.2.2 on 2023-06-20 10:26

import accessibility.db
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0035_remove_all_in_one_accessibility_aioa_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_icon_size",
            field=accessibility.db.RadioGridField(
                help_text='<script>const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size_0"]\');\n    const sizeOptionsImg = document.querySelectorAll(\'.csticontype\');\n    const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type_0"]\');\n    typeOptions.forEach(option => {\n        option.addEventListener("click", (event) => {\n            sizeOptionsImg.forEach(option2 => {\n                var ico_type = document.querySelector(\'input[name="aioa_icon_type_0"]:checked\').value;\n                option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n            });\n        });\n    });</script>',
                require_all_fields=False,
                rows=((1, ""),),
                values=[
                    (
                        "aioa-big-icon",
                        '<img class="csticontype"  src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="75" height="75" />',
                    ),
                    (
                        "aioa-medium-icon",
                        '<img class="csticontype"src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-default-icon",
                        '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="55" height="55" />',
                    ),
                    (
                        "aioa-small-icon",
                        '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="45" height="45" />',
                    ),
                    (
                        "aioa-extra-small-icon",
                        '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="35" height="35"/>',
                    ),
                ],
                verbose_name="Icon Size",
            ),
        ),
    ]
