# Generated by Django 4.2 on 2023-06-21 13:16

import accessibility.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accessibility", "0044_alter_all_in_one_accessibility_aioa_license_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_in_one_accessibility",
            name="aioa_license_Key",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="<span class='validate_pro'><p>You are currently using Free version which have limited features. </br>Please <a href='https://www.skynettechnologies.com/add-ons/product/all-in-one-accessibility/'>purchase</a> License Key for additional features on the ADA Widget</p></span><script>if(document.querySelector('#id_aioa_license_Key').value != ''){document.querySelector('.validate_pro').style.display='none';} else {document.querySelector('.validate_pro').style.display='block';} </script>",
                max_length=150,
                validators=[accessibility.models.validate_token],
                verbose_name="License Key",
            ),
        ),
    ]
