# Generated by Django 3.2.20 on 2023-08-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0050_alter_all_in_one_accessibility_aioa_icon_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_in_one_accessibility',
            name='aioa_icon_mobile',
        ),
    ]
