# Generated by Django 3.2.20 on 2023-09-18 06:13

import accessibility.db
import accessibility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0052_alter_all_in_one_accessibility_aioa_icon_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_in_one_accessibility',
            name='aioa_icon_size',
            field=accessibility.db.RadioGridField(default=('aioa-default-icon', '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="55" height="55" />'), help_text='    \n    <script>\n    const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size_0"]\');\n    console.log(sizeOptions)\n    const sizeOptionsImg = document.querySelectorAll(\'.csticontype\');\n    const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type_0"]\');\n    typeOptions.forEach(option => {\n        option.addEventListener("click", (event) => {\n            sizeOptionsImg.forEach(option2 => {\n                var ico_type = document.querySelector(\'input[name="aioa_icon_type_0"]:checked\').value;\n                option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n            });\n        });\n    });\n</script>\n\n<script>\n\n      if(document.querySelector("#id_aioa_license_Key").value != \'\')\n      {\n          document.querySelector(\'div[class="form-row field-aioa_icon_type"]\').style.display=\'block\';\n          document.querySelector(\'div[class="form-row field-aioa_icon_size"]\').style.display=\'block\';\n          document.querySelector(\'div[class="form-row field-aioa_color_code"]\').style.display=\'block\';\n          document.querySelector(\'div[class="form-row field-aioa_place"]\').style.display=\'block\';\n\n      }\n      else\n      {\n          document.querySelector(\'div[class="form-row field-aioa_icon_type"]\').style.display=\'none\';\n          document.querySelector(\'div[class="form-row field-aioa_icon_size"]\').style.display=\'none\';\n          document.querySelector(\'div[class="form-row field-aioa_color_code"]\').style.display=\'none\';\n          document.querySelector(\'div[class="form-row field-aioa_place"]\').style.display=\'none\';\n\n      }\n      </script>\n', require_all_fields=False, rows=((1, ''),), values=[('aioa-big-icon', '<img class="csticontype"  src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="75" height="75" />'), ('aioa-medium-icon', '<img class="csticontype"src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />'), ('aioa-default-icon', '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="55" height="55" />'), ('aioa-small-icon', '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="45" height="45" />'), ('aioa-extra-small-icon', '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="35" height="35"/>')], verbose_name='Icon Size For Desktop'),
        ),
        migrations.AlterField(
            model_name='all_in_one_accessibility',
            name='aioa_icon_type',
            field=accessibility.db.RadioGridField(default=('aioa-icon-type-1', '<img  src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />'), help_text='', require_all_fields=False, rows=((1, ''),), values=[('aioa-icon-type-1', '<img  src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />'), ('aioa-icon-type-2', '<img  src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-2.svg" width="65" height="65" />'), ('aioa-icon-type-3', '<img  src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-3.svg" width="65" height="65" />')], verbose_name='Icon Type'),
        ),
        migrations.AlterField(
            model_name='all_in_one_accessibility',
            name='aioa_license_Key',
            field=models.CharField(blank=True, default=None, help_text="<span style='font-size:15px;' class='validate_pro'>Please <a href=https://ada.skynettechnologies.us/trial-subscription?utm_source=#Website-domain#&utm_medium=#platform name#-module&utm_campaign=trial-subscription target=_blank>subscribe</a> for a 10 days free trial and receive a license key to enable 52+ features of All in One Accessibility Pro.<br>No payment charged upfront, Cancel anytime</span><script>if(document.querySelector('#id_aioa_license_Key').value != ''){document.querySelector('.validate_pro').style.display='none';} else {document.querySelector('.validate_pro').style.display='block';} </script>", max_length=150, validators=[accessibility.models.validate_token], verbose_name='License Key'),
        ),
    ]
